image: maven:3.6.1

pipelines:
  branches:
    master:
      - step:
          script:
            - mvn -X clean install -f atlassian-intellij-connector/pom.xml
  default:
    - step:
        script:
            - echo "Building only on the master branch"
